class WordHints {
  static final Map<String, String> hints = {
    // Easy Words
    'apple': 'It grows on trees and can be red or green',
    'house': 'A place where people live',
    'water': 'You need this to survive but it/’s not food',
    'music': 'Heard but not seen, moves the soul',
    'happy': 'An emotion you feel when things go well',
    'smile': 'Often shared when joyful or amused',
    'light': 'Makes darkness disappear',
    'dream': 'What you experience in sleep or aim for in life',
    'peace': 'The opposite of conflict',
    'heart': 'It beats inside you and symbolizes love',
    'cloud': 'It floats above and can bring rain',
    'beach': 'Where land meets the sea with sand',
    'chair': 'Used for sitting, often at a desk',
    'table': 'Where meals or meetings often happen',
    'phone': 'It rings and lets you talk to others',
    'bread': 'Often sliced and used for sandwiches',
    'candy': 'Sweet and small, often wrapped',
    'stars': 'Seen in the night sky, not the famous kind',
    'juice': 'A drink squeezed from fruits',
    'green': 'A color you see in grass',
    'clock': 'Keeps ticking and shows the time',
    'piano': 'An instrument with keys, not for doors',
    'dance': 'Movement often done to music',
    'movie': 'Seen on screens, tells a story',
    'plant': 'Grows in soil and needs sunlight',
    'shirt': 'Worn on the upper body',
    'socks': 'Keeps your feet warm under shoes',
    'books': 'Full of pages and stories',
    'teeth': 'You use them to chew',
    'zebra': 'A striped animal found in Africa',
    'lemon': 'Sour fruit, yellow in color',
    'grass': 'Soft green cover on the ground',
    'paint': 'Used to add color to surfaces',
    'tiger': 'Big striped cat, very powerful',
    'grape': 'Tiny fruit, often in bunches',
    'spoon': 'Used to eat soup or cereal',
    'couch': 'A soft seat for multiple people',
    'truck': 'A big vehicle used for carrying goods',
    'mouse': 'Tiny rodent or computer accessory',
    'panda': 'Black and white bear that eats bamboo',
    'towel': 'Used after a bath or swim',
    'drums': 'They make a beat when hit',
    'glove': 'Worn on hands, especially in winter',
    'floor': 'You walk on it',
    'purse': 'Carries personal items, often with straps',
    'brush': 'Used for hair or painting',
    'ruler': 'Measures straight lines in inches or cm',
    'sugar': 'Sweet but not healthy in excess',
    'honey': 'Made by bees and used in tea',
    'earth': 'The planet we live on',
    'cabin': 'A small house, often in woods',
    'crown': 'Worn by royalty on the head',
    'drink': 'Not food, but can quench thirst',
    'paper': 'You write or draw on it',
    'block': 'A cube-shaped toy or object',
    'crayon': 'Used by kids to color',
    'flame': 'Small fire, flickers with heat',
    'jelly': 'Wobbly and sweet, often fruity',
    'radio': 'Plays music without a screen',
    'scarf': 'Worn around the neck, stylish or warm',
    'shelf': 'Holds books or objects up high',
    'space': 'Vast, dark, full of stars',
    'whale': 'Biggest creature in the ocean',
    'train': 'Long and rides on tracks',
    'snack': 'Not a meal but keeps you going',
    'tooth': 'One of many in your mouth',
    'woods': 'Where many trees grow together',
    'sheep': 'Woolly and often herded',
    'swing': 'Found on playgrounds and goes back and forth',
    'track': 'Runners use this in competitions',
    'petal': 'Part of a flower, often colorful',
    'field': 'Open area of grass or crops',
    'queen': 'Female royal leader',
    'match': 'Used to start fire, or pair items',
    'flute': 'Woodwind instrument, held sideways',
    'lunch': 'Eaten between breakfast and dinner',
    'berry': 'Small, juicy fruit',
    'boots': 'Worn in snow or rain',
    'pouch': 'Small bag that holds things',
    'scoop': 'Takes up ice cream or flour',
    'noise': 'Any sound, often loud or unwanted',
    'story': 'Tells events real or imagined',
    'shell': 'Found on beaches, once home to sea life',
    'fruit': 'Natural, sweet food from trees',
    'wagon': 'Has wheels and often pulled by kids',
    'drill': 'Makes holes, noisy tool',
    'chalk': 'Writes on boards, breaks easily',
    'broom': 'For cleaning without water',
    'knife': 'Can be sharp and useful',

    // Medium Words
    'garden': 'A place where plants and flowers grow',
    'purple': 'A color made by mixing red and blue',
    'orange': 'A color and a citrus fruit',
    'yellow': 'The color of the sun and bananas',
    'window': 'Lets light in and lets you see outside',
    'pencil': 'Used for writing, has a pointy end',
    'school': 'Where children go to learn',
    'friend': 'Someone you like and spend time with',
    'family': 'People related to you by blood or marriage',
    'summer': 'The hottest season of the year',
    'winter': 'The coldest season with snow',
    'spring': 'Season when flowers bloom',
    'autumn': 'Season when leaves fall',
    'dinner': 'The main meal of the day',
    'breakfast': 'First meal of the day',
    'pillow': 'Soft support for your head when sleeping',
    'castle': 'Large, fortified building from medieval times',
    'bridge': 'Structure that crosses over water or gaps',
    'flower': 'Colorful part of a plant',
    'rocket': 'Vehicle that goes to space',
    'planet': 'Large body that orbits a star',
    'ticket': 'Piece of paper that lets you enter',
    'butter': 'Dairy product used in cooking',
    'banana': 'Yellow curved fruit',
    'glider': 'Aircraft without an engine',
    'jungle': 'Dense, tropical forest',
    'mirror': 'Reflects your image',
    'silver': 'Shiny metal used in jewelry',
    'cheese': 'Dairy product made from milk',
    'artist': 'Someone who creates art',
    'circle': 'Perfect round shape',
    'animal': 'Living creature that moves',
    'cookie': 'Sweet baked treat',
    'kitten': 'Baby cat',
    'sister': 'Female sibling',
    'candle': 'Wax stick with a wick for light',
    'guitar': 'Stringed musical instrument',
    'hunter': 'Someone who hunts animals',
    'bucket': 'Container with a handle',
    'engine': 'Machine that converts energy into motion',
    'travel': 'Going from one place to another',
    'forest': 'Large area covered with trees',
    'rabbit': 'Small hopping animal with long ears',
    'closet': 'Small room for storing clothes',
    'button': 'Small fastener for clothes',
    'pickle': 'Preserved cucumber',
    'goblet': 'Fancy drinking cup',
    'magnet': 'Attracts metal objects',
    'pirate': 'Sea robber',
    'feather': 'Light growth on a bird',
    'island': 'Land surrounded by water',
    'sunset': 'When the sun goes down',
    'statue': 'Sculpture of a person or animal',
    'wallet': 'Holds money and cards',
    'blanket': 'Keeps you warm in bed',
    'voyage': 'Long journey by sea',
    'garage': 'Where you park your car',
    'laptop': 'Portable computer',
    'handle': 'Part you hold onto',
    'bottle': 'Container for liquids',
    'finger': 'Part of your hand',
    'pastel': 'Soft, light color',
    'saddle': 'Seat for riding a horse',
    'temple': 'Place of worship',
    'ladder': 'Used to climb up high',
    'shovel': 'Tool for digging',
    'helmet': 'Protects your head',
    'throat': 'Part of your neck',
    'camera': 'Takes photographs',
    'farmer': 'Grows crops and raises animals',
    'vessel': 'Container or ship',
    'lantern': 'Portable light source',
    'tablet': 'Small computer or medicine',
    'rubber': 'Elastic material',
    'parrot': 'Colorful talking bird',
    'napkin': 'Used at meals',
    'outfit': 'Set of clothes',
    'cactus': 'Spiky desert plant',
    'cereal': 'Breakfast food',
    'cousin': 'Child of your aunt or uncle',
    'market': 'Place to buy things',
    'singer': 'Person who sings',
    'shower': 'Bath with falling water',
    'vacuum': 'Cleans by sucking up dirt',
    'puzzle': 'Game that tests your mind',
    'donkey': 'Animal similar to a horse',
    'bubble': 'Round ball of air in liquid',

    // Hard Words
    'beautiful': 'Very pleasing to look at',
    'chocolate': 'Sweet treat made from cocoa',
    'elephant': 'Large animal with a trunk',
    'giraffe': 'Tall animal with a long neck',
    'butterfly': 'Insect with colorful wings',
    'dinosaur': 'Prehistoric reptile',
    'umbrella': 'Protects from rain',
    'computer': 'Electronic device for processing data',
    'keyboard': 'Used to type on a computer',
    'notebook': 'Book for writing notes',
    'calendar': 'Shows days and months',
    'birthday': 'Anniversary of your birth',
    'holiday': 'Day of celebration',
    'vacation': 'Time off from work or school',
    'adventure': 'Exciting experience',
    'backpack': 'Bag carried on your back',
    'carousel': 'Rotating amusement ride',
    'triangle': 'Shape with three sides',
    'building': 'Structure with walls and a roof',
    'alligator': 'Large reptile with a long snout',
    'binoculars': 'Used to see things far away',
    'volcano': 'Mountain that erupts',
    'mountains': 'Large natural elevations',
    'sandwich': 'Food between two slices of bread',
    'firework': 'Explosive display in the sky',
    'chandelier': 'Decorative hanging light',
    'hurricane': 'Powerful tropical storm',
    'microwave': 'Heats food quickly',
    'astronaut': 'Person who travels in space',
    'refrigerator': 'Keeps food cold',
    'telephone': 'Device for talking to others',
    'whirlpool': 'Spinning water current',
    'playground': 'Place for children to play',
    'snowflake': 'Unique ice crystal',
    'blueberry': 'Small blue fruit',
    'lighthouse': 'Guides ships at sea',
    'calculator': 'Device for doing math',
    'reception': 'Welcome area or party',
    'celebrate': 'To mark a special occasion',
    'campfire': 'Outdoor fire for cooking',
    'scarecrow': 'Keeps birds away from crops',
    'helicopter': 'Aircraft with rotating blades',
    'electricity': 'Form of energy',
    'conversation': 'Talk between people',
    'revolution': 'Complete turn or major change',
    'motorcycle': 'Two-wheeled vehicle',
    'construction': 'Building process',
    'electrician': 'Works with electrical systems',
    'information': 'Knowledge or data',
    'vocabulary': 'Words you know',
    'destination': 'Place you\'re going to',
    'microscope': 'Magnifies small objects',
    'contribution': 'Something you give or add',
    'grandmother': 'Mother of your parent',
    'friendship': 'Relationship between friends',
    'distribution': 'Spreading things out',
    'imagination': 'Ability to create mental images',
    'personality': 'Your character traits',
    'investigate': 'To look into something',
    'controller': 'Device for controlling games',
    'submarine': 'Underwater vessel',
    'population': 'Number of people in an area',
    'temperature': 'Measure of heat',
    'volleyball': 'Sport played with a net',
    'relationship': 'Connection between people',
    'photograph': 'Picture taken with a camera',
    'instrument': 'Device for making music',
    'technology': 'Application of scientific knowledge',
    'navigation': 'Finding your way',
    'journalist': 'Reports news',
    'invention': 'New creation or device',
    'compass': 'Shows direction',
    'philosophy': 'Study of fundamental questions',
    'understand': 'To comprehend',
    'windshield': 'Front window of a car',
    'lightbulb': 'Produces light',
    'chocolatey': 'Tasting like chocolate',
    'typography': 'Art of arranging type',
    'basketball': 'Sport with a hoop',
    'restaurant': 'Place to eat out',
    'sunscreen': 'Protects from sunburn',
    'earthquake': 'Shaking of the ground',
    'skyscraper': 'Very tall building',
    'achievement': 'Something accomplished',
    'architecture': 'Design of buildings',
    'foundation': 'Base of a building',
    'conclusion': 'End or result',
    'nightlight': 'Small light for darkness',
    'experiment': 'Scientific test',
    'backpacker': 'Person who travels with a backpack',
    'interview': 'Formal meeting',
    'definition': 'Meaning of a word',
    'civilization': 'Advanced society',
    'democracy': 'Government by the people',
  };

  static String getHint(String word) {
    return hints[word.toLowerCase()] ?? 'No hint available for this word';
  }
} 